import pandas as pd

new_data = [
    # c03 Plant Kingdom
    ["BIO-C03-01", "c03", "Plant Kingdom", "Algae", "Algae Classification & Pigments", "Algae are chlorophyll-bearing, simple, thalloid, autotrophic and largely aquatic organisms. They are classified into Chlorophyceae (Green), Phaeophyceae (Brown), and Rhodophyceae (Red) primarily based on their pigment composition.", "Step 1: Chlorophyceae contain chl a and b. Step 2: Phaeophyceae contain chl a, c, and fucoxanthin. Step 3: Rhodophyceae contain chl a, d, and phycoerythrin.", "NEET Trap: Volvox is a colonial green alga, not unicellular like Chlamydomonas. Red algae have non-motile gametes.", "Which pigment is responsible for the red colour of Rhodophyceae?", "Phycocyanin|Fucoxanthin|Phycoerythrin|Chlorophyll b", 2, "Phycoerythrin is the major accessory pigment in red algae that gives them their characteristic red colour."],
    ["BIO-C03-02", "c03", "Plant Kingdom", "Bryophytes", "Amphibians of Plant Kingdom", "Bryophytes are called amphibians of the plant kingdom because these plants can live in soil but are dependent on water for sexual reproduction.", "Step 1: Main plant body is haploid gametophyte. Step 2: Antherozoids are released into water. Step 3: Zygote forms a multicellular diploid sporophyte, which is attached to and dependent on the gametophyte.", "NEET Trap: The sporophyte of bryophytes is not free-living; it is attached to the photosynthetic gametophyte and derives nourishment from it.", "In bryophytes, the sporophyte is:", "Free-living and independent|Parasitic on gametophyte|Haploid|Formed after meiosis in zygote", 1, "The sporophyte in bryophytes is not free-living but attached to the photosynthetic gametophyte and derives nourishment from it."],
    ["BIO-C03-03", "c03", "Plant Kingdom", "Pteridophytes", "First Vascular Land Plants", "Pteridophytes are the first terrestrial plants to possess vascular tissues (xylem and phloem). They include horsetails and ferns.", "Step 1: Main plant body is a diploid sporophyte differentiated into true roots, stem and leaves. Step 2: Sporangia produce spores by meiosis. Step 3: Spores germinate into an inconspicuous, small, multicellular, free-living, mostly photosynthetic thalloid gametophyte called prothallus.", "NEET Trap: In pteridophytes, the main plant body is a sporophyte, whereas in bryophytes it is a gametophyte. Also, prothallus is free-living.", "The prothallus in pteridophytes represents:", "Sporophytic generation|Male reproductive organ|Free-living gametophyte|Diploid structure", 2, "Prothallus is the inconspicuous, multicellular, free-living, mostly photosynthetic thalloid gametophyte in pteridophytes."],
    ["BIO-C03-04", "c03", "Plant Kingdom", "Gymnosperms", "Naked Seed Plants", "Gymnosperms are plants in which the ovules are not enclosed by any ovary wall and remain exposed, both before and after fertilization.", "Step 1: Roots are generally tap roots; some have fungal association (mycorrhiza in Pinus) or coralloid roots with N2-fixing cyanobacteria (Cycas). Step 2: Leaves are well-adapted to withstand extremes of temperature, humidity and wind. Step 3: Heterosporous; produce haploid microspores and megaspores.", "NEET Trap: Cycas has unbranched stems and pinnate leaves, while Pinus has branched stems and needle-like leaves.", "Which of the following gymnosperms has coralloid roots associated with N2-fixing cyanobacteria?", "Pinus|Cycas|Ginkgo|Cedrus", 1, "Cycas has specialized coralloid roots that harbour nitrogen-fixing cyanobacteria like Anabaena."],

    # c04 Animal Kingdom
    ["BIO-C04-01", "c04", "Animal Kingdom", "Porifera", "Sponges & Canal System", "Members of phylum Porifera are commonly known as sponges. They are generally marine, asymmetrical animals with cellular level of organisation.", "Step 1: Water enters through minute pores (ostia) in the body wall. Step 2: Water enters a central cavity (spongocoel). Step 3: Water goes out through the osculum. This pathway helps in food gathering, respiratory exchange and removal of waste.", "NEET Trap: Choanocytes (collar cells) line the spongocoel and the canals. Sponges have intracellular digestion.", "The water vascular system is characteristic of echinoderms, while the canal system is found in:", "Porifera|Cnidaria|Annelida|Arthropoda", 0, "Sponges (Porifera) possess a water transport or canal system, whereas echinoderms have a water vascular system."],
    ["BIO-C04-02", "c04", "Animal Kingdom", "Cnidaria", "Cnidoblasts & Alternation of Generation", "Cnidarians (coelenterates) are aquatic, mostly marine, sessile or free-swimming, radially symmetrical animals characterized by the presence of cnidoblasts.", "Step 1: Cnidoblasts contain stinging capsules (nematocysts) used for anchorage, defense and capture of prey. Step 2: Some exhibit metagenesis (Obelia), where polyps produce medusae asexually and medusae form polyps sexually.", "NEET Trap: Metamerism is true segmentation found in Annelida, Arthropoda, and Chordata. Metagenesis is alternation of generation found in Cnidaria.", "Which of the following exhibits metagenesis?", "Hydra|Obelia|Adamsia|Aurelia", 1, "Obelia exhibits metagenesis, alternating between the asexual polyp phase and the sexual medusa phase."],
    ["BIO-C04-03", "c04", "Animal Kingdom", "Arthropoda", "Largest Phylum", "Arthropoda is the largest phylum of Animalia which includes insects. Over two-thirds of all named species on earth are arthropods.", "Step 1: Organ-system level of organisation, bilaterally symmetrical, triploblastic, segmented and coelomate. Step 2: Body covered by chitinous exoskeleton. Step 3: Body consists of head, thorax and abdomen. They have jointed appendages.", "NEET Trap: Respiration occurs through gills, book gills, book lungs or tracheal system. Statocysts (balance organs) are present.", "The exoskeleton of arthropods is composed of:", "Calcium carbonate|Silica|Chitin|Cellulose", 2, "Arthropods have a tough exoskeleton made of chitin, a complex nitrogenous polysaccharide."],
    ["BIO-C04-04", "c04", "Animal Kingdom", "Chordata", "Features of Chordates", "Phylum Chordata is characterized by the presence of a notochord, a dorsal hollow nerve cord and paired pharyngeal gill slits.", "Step 1: Bilaterally symmetrical, triploblastic, coelomate with organ-system level of organisation. Step 2: Possess a post-anal tail and closed circulatory system. Step 3: Divided into Urochordata, Cephalochordata, and Vertebrata.", "NEET Trap: All vertebrates are chordates but all chordates are not vertebrates. In Urochordata, notochord is present only in larval tail.", "In which subphylum is the notochord present only in the larval tail?", "Cephalochordata|Urochordata|Vertebrata|Hemichordata", 1, "In Urochordata (Tunicata), the notochord is restricted to the larval tail and is lost in the adult."],

    # c05 Morphology of Flowering Plants
    ["BIO-C05-01", "c05", "Morphology of Flowering Plants", "Root Modifications", "Storage & Support Roots", "Roots in some plants change their shape and structure and become modified to perform functions other than absorption and conduction of water and minerals.", "Step 1: Tap roots of carrot, turnip and adventitious roots of sweet potato get swollen and store food. Step 2: Prop roots of banyan tree provide support. Step 3: Stilt roots in maize and sugarcane come from lower nodes of stem. Step 4: Pneumatophores in Rhizophora grow vertically upward for oxygen.", "NEET Trap: Sweet potato is a modified adventitious root, while potato is a modified stem.", "Pneumatophores are helpful in:", "Transpiration|Getting oxygen for respiration|Vegetative reproduction|Providing mechanical support", 1, "Pneumatophores are modified roots in mangrove plants like Rhizophora that grow upwards to get oxygen for respiration."],
    ["BIO-C05-02", "c05", "Morphology of Flowering Plants", "Stem Modifications", "Underground & Aerial Modifications", "Stems are modified to perform functions of storage of food, support, protection and of vegetative propagation.", "Step 1: Underground stems of potato, ginger, turmeric, zaminkand, colocasia are modified to store food. Step 2: Stem tendrils (axillary bud) in gourds and grapevines. Step 3: Thorns in Citrus and Bougainvillea. Step 4: Phylloclade in Opuntia (flattened) and Euphorbia (cylindrical).", "NEET Trap: Thorns are modified axillary buds, whereas spines (e.g. in cactus) are modified leaves.", "Which of the following is a modified stem for protection?", "Tendril|Phylloclade|Thorn|Pneumatophore", 2, "Thorns are hard, woody, straight and pointed structures modified from axillary buds for protection against browsing animals."],
    ["BIO-C05-03", "c05", "Morphology of Flowering Plants", "Leaf Venation & Phyllotaxy", "Arrangement of Leaves", "Venation is the arrangement of veins in the lamina. Phyllotaxy is the pattern of arrangement of leaves on the stem or branch.", "Step 1: Reticulate venation is common in dicots; parallel venation is common in monocots. Step 2: Alternate phyllotaxy (China rose, mustard, sunflower) - single leaf at each node. Step 3: Opposite (Calotropis, guava) - pair of leaves at each node. Step 4: Whorled (Alstonia) - more than two leaves at a node.", "NEET Trap: Smilax is a monocot with reticulate venation, and Calophyllum is a dicot with parallel venation (exceptions often tested implicitly).", "In which plant is whorled phyllotaxy found?", "Mustard|China rose|Guava|Alstonia", 3, "In Alstonia, more than two leaves arise at a node and form a whorl."],
    ["BIO-C05-04", "c05", "Morphology of Flowering Plants", "Placentation", "Types of Placentation", "The arrangement of ovules within the ovary is known as placentation.", "Step 1: Marginal (pea). Step 2: Axile (china rose, tomato, lemon) - multilocular ovary. Step 3: Parietal (mustard, Argemone) - ovules on inner wall, often forming a false septum (replum). Step 4: Free central (Dianthus, Primrose). Step 5: Basal (sunflower, marigold) - single ovule at the base.", "NEET Trap: Replum (false septum) is a characteristic of parietal placentation in mustard and Argemone, not axile placentation.", "A false septum (replum) is found in the ovary of:", "Tomato|Dianthus|Mustard|Pea", 2, "In mustard and Argemone, the ovary is initially one-chambered but becomes two-chambered due to the formation of a false septum (replum)."],

    # c06 Anatomy of Flowering Plants
    ["BIO-C06-01", "c06", "Anatomy of Flowering Plants", "Meristematic Tissues", "Apical, Intercalary & Lateral Meristems", "Meristems are regions of active cell division. They are responsible for the primary and secondary growth of the plant.", "Step 1: Apical meristems occur at tips of roots and shoots (primary growth). Step 2: Intercalary meristems occur between mature tissues (e.g. grasses). Step 3: Lateral meristems (cylindrical) like vascular cambium and cork cambium cause secondary growth.", "NEET Trap: Both apical and intercalary meristems are primary meristems because they appear early in life and contribute to the primary plant body.", "Which meristem is responsible for regenerating parts removed by grazing herbivores in grasses?", "Apical meristem|Lateral meristem|Intercalary meristem|Secondary meristem", 2, "Intercalary meristems occur at the base of internodes or leaves in grasses and regenerate parts removed by grazing."],
    ["BIO-C06-02", "c06", "Anatomy of Flowering Plants", "Permanent Tissues", "Xylem & Phloem Elements", "Complex permanent tissues are made of more than one type of cells and work together as a unit.", "Step 1: Xylem consists of tracheids, vessels, xylem fibres, and xylem parenchyma. Step 2: Vessels are characteristic of angiosperms (mostly absent in gymnosperms). Step 3: Phloem consists of sieve tube elements, companion cells, phloem parenchyma, and phloem fibres.", "NEET Trap: Gymnosperms lack vessels in their xylem and lack sieve tubes and companion cells in their phloem (they have albuminous cells and sieve cells).", "Which of the following is present in angiosperms but generally absent in gymnosperms?", "Tracheids|Vessels|Sieve cells|Xylem parenchyma", 1, "Vessels in xylem and sieve tube elements/companion cells in phloem are characteristic features of angiosperms, generally lacking in gymnosperms."],
    ["BIO-C06-03", "c06", "Anatomy of Flowering Plants", "Dicot vs Monocot Root", "Internal Structure of Roots", "The anatomical features distinguish dicot and monocot roots based on vascular bundles and pith.", "Step 1: Dicot root has 2-4 xylem and phloem patches (diarch to tetrarch); small or inconspicuous pith. Step 2: Monocot root has more than six xylem bundles (polyarch); large and well-developed pith. Step 3: Endodermis with Casparian strips (suberin) is present in both.", "NEET Trap: Pith is large and well-developed in monocot root and dicot stem, but inconspicuous in dicot root.", "A polyarch xylem with a large, well-developed pith is characteristic of:", "Dicot stem|Monocot root|Dicot root|Monocot stem", 1, "Monocot roots typically have polyarch vascular bundles (more than 6 xylem patches) and a prominent central pith."],
    ["BIO-C06-04", "c06", "Anatomy of Flowering Plants", "Secondary Growth", "Vascular Cambium & Cork Cambium", "Secondary growth increases the girth (thickness) of the plant organs, primarily occurring in dicot stems and dicot roots.", "Step 1: Vascular cambium forms a complete ring from intrafascicular and interfascicular cambium. Step 2: It cuts off secondary xylem towards the inside and secondary phloem towards the outside. Step 3: Cork cambium (phellogen) develops in the cortex, producing cork (phellem) outside and secondary cortex (phelloderm) inside.", "NEET Trap: Heartwood (dark, central, dead, contains tannins/resins, does not conduct water) vs. Sapwood (lighter, outer, living/functional, conducts water).", "The tissues phellem, phellogen, and phelloderm are collectively known as:", "Pericycle|Periderm|Bark|Stele", 1, "Phellogen (cork cambium), phellem (cork), and phelloderm (secondary cortex) collectively constitute the periderm."],

    # c07 Structural Organisation in Animals
    ["BIO-C07-01", "c07", "Structural Organisation in Animals", "Epithelial Tissue", "Types of Epithelium", "Epithelial tissue provides a covering or lining for some parts of the body.", "Step 1: Squamous (flattened) - walls of blood vessels and air sacs of lungs (diffusion). Step 2: Cuboidal (cube-like) - ducts of glands, tubular parts of nephrons (secretion/absorption). Step 3: Columnar (tall) - lining of stomach and intestine. Step 4: Ciliated - inner surface of bronchioles and fallopian tubes.", "NEET Trap: PCT of nephron has simple cuboidal epithelium with microvilli (brush border), which increases surface area for absorption.", "Ciliated columnar epithelium is found in the inner lining of:", "Fallopian tubes|Blood vessels|Stomach|Bile duct", 0, "Ciliated epithelium is found in the inner lining of hollow organs like bronchioles and fallopian tubes to move particles or mucus in a specific direction."],
    ["BIO-C07-02", "c07", "Structural Organisation in Animals", "Connective Tissue", "Areolar, Adipose & Dense Connective", "Connective tissues are the most abundant and widely distributed in the body of complex animals.", "Step 1: Loose connective - Areolar (beneath skin, support framework) and Adipose (fat storage). Step 2: Dense connective - Dense regular (tendons, ligaments) and Dense irregular (skin). Step 3: Specialised - Cartilage, Bone, Blood.", "NEET Trap: Tendons connect skeletal muscle to bone; ligaments connect bone to bone. Both are dense regular connective tissues.", "Which of the following is a loose connective tissue?", "Cartilage|Tendon|Areolar tissue|Bone", 2, "Areolar tissue is a loose connective tissue located beneath the skin, often serving as a support framework for epithelium."],
    ["BIO-C07-03", "c07", "Structural Organisation in Animals", "Muscle Tissue", "Skeletal, Smooth & Cardiac", "Muscle tissue is responsible for movement and is made of long, cylindrical fibres.", "Step 1: Skeletal muscle - striated, voluntary, multinucleated, attached to bones. Step 2: Smooth muscle - non-striated, involuntary, spindle-shaped, uninucleate, in walls of internal organs. Step 3: Cardiac muscle - striated, involuntary, branched, with intercalated discs (communication junctions).", "NEET Trap: Intercalated discs are unique to cardiac muscle. Smooth muscle lacks striations and is involuntary.", "Intercalated discs are characteristic of which tissue?", "Skeletal muscle|Smooth muscle|Cardiac muscle|Nervous tissue", 2, "Cardiac muscle tissue features intercalated discs at cell junctions, which allow the cells to contract as a unit."],
    ["BIO-C07-04", "c07", "Structural Organisation in Animals", "Cockroach Anatomy", "Digestive & Excretory System of Periplaneta", "Cockroach (Periplaneta americana) exhibits distinct organ systems adapted for terrestrial life.", "Step 1: Foregut includes crop (storage) and gizzard/proventriculus (grinding food using chitinous teeth). Step 2: Hepatic caeca (6-8 blind tubules) at foregut-midgut junction secrete digestive juices. Step 3: Malpighian tubules (100-150 yellow tubules) at midgut-hindgut junction help in excretion of uric acid.", "NEET Trap: Hepatic caeca are at the junction of foregut and midgut; Malpighian tubules are at the junction of midgut and hindgut. Cockroach is uricotelic.", "In cockroach, the Malpighian tubules are located at the junction of:", "Foregut and midgut|Midgut and hindgut|Crop and gizzard|Oesophagus and crop", 1, "Malpighian tubules are excretory organs present at the junction of the midgut and hindgut in cockroaches."],
]

df = pd.read_csv('data/neet_knowledge_base.csv')
new_df = pd.DataFrame(new_data, columns=df.columns)
df = pd.concat([df, new_df], ignore_index=True)
df.to_csv('data/neet_knowledge_base.csv', index=False)
print("Added c03 to c07. Total rows:", len(df))
