import pandas as pd

new_data = [
    # c01 The Living World (2)
    ["BIO-C01-02", "c01", "The Living World", "Taxonomic Categories", "Hierarchy & Species Concept", "Taxonomic categories are a series of distinct ranks or levels in the hierarchical classification of organisms.", "Step 1: Species is the lowest category (basic unit of classification). Step 2: Genus comprises a group of related species. Step 3: Family has a group of related genera. Step 4: Order, Class, Phylum/Division, and Kingdom follow in ascending order.", "NEET Trap: As we go higher from species to kingdom, the number of common characteristics goes on decreasing.", "As we go from species to kingdom in a taxonomic hierarchy, the number of common characteristics:", "Will decrease|Will increase|Remain same|May increase or decrease", 0, "The lower the taxa, the more are the characteristics that the members within the taxon share. Higher the category, greater is the difficulty of determining the relationship to other taxa at the same level."],
    ["BIO-C01-03", "c01", "The Living World", "Taxonomical Aids", "Herbarium & Botanical Gardens", "Taxonomic aids are collections of samples or preserved organisms which help in extensive research for identification.", "Step 1: Herbarium is a storehouse of collected plant specimens that are dried, pressed and preserved on sheets. Step 2: Botanical gardens have collections of living plants for reference. Step 3: Museum has collections of preserved plant and animal specimens for study and reference. Step 4: Zoological Parks are places where wild animals are kept in protected environments.", "NEET Trap: Herbarium sheets carry a label providing information about date/place of collection, English, local and botanical names, family, collector's name, but NOT the height of the plant.", "The label of a herbarium sheet does NOT carry information on:", "Date of collection|Name of collector|Local names|Height of the plant", 3, "The standard herbarium label includes date/place of collection, English, local and botanical names, family, and collector's name, but not the height of the plant."],

    # c02 Biological Classification (3)
    ["BIO-C02-02", "c02", "Biological Classification", "Kingdom Monera", "Archaebacteria & Eubacteria", "Kingdom Monera comprises all prokaryotic organisms, primarily bacteria, which are the most abundant micro-organisms.", "Step 1: Archaebacteria live in harsh habitats (halophiles, thermoacidophiles, methanogens) due to a different cell wall structure. Step 2: Eubacteria (true bacteria) have a rigid cell wall and, if motile, a flagellum. Step 3: Cyanobacteria (blue-green algae) have chlorophyll a and perform oxygenic photosynthesis; some fix nitrogen in heterocysts.", "NEET Trap: Methanogens are present in the gut of several ruminant animals and produce methane. Heterocysts in Nostoc and Anabaena fix atmospheric nitrogen.", "Which of the following are found in extreme saline conditions?", "Eubacteria|Cyanobacteria|Mycobacteria|Archaebacteria", 3, "Archaebacteria known as halophiles are uniquely adapted to survive in extreme saline conditions due to their specialized cell wall structure."],
    ["BIO-C02-03", "c02", "Biological Classification", "Kingdom Protista", "Chrysophytes & Dinoflagellates", "Protista includes all single-celled eukaryotes. The boundaries of this kingdom are not well-defined.", "Step 1: Chrysophytes (Diatoms & Golden algae/Desmids) have indestructible cell walls embedded with silica (diatomaceous earth). Step 2: Dinoflagellates are mostly marine/photosynthetic with stiff cellulose plates on the outer surface (red tides by Gonyaulax). Step 3: Euglenoids have a protein-rich pellicle instead of a cell wall. Step 4: Slime moulds are saprophytic.", "NEET Trap: Diatomaceous earth is formed by the accumulation of indestructible silica cell walls of diatoms over billions of years.", "Which organisms are the chief producers in the oceans?", "Dinoflagellates|Diatoms|Cyanobacteria|Euglenoids", 1, "Diatoms (part of Chrysophytes) are microscopic, float passively in water currents (plankton), and are the chief producers in the oceans."],
    ["BIO-C02-04", "c02", "Biological Classification", "Viruses & Viroids", "Acellular Entities", "Viruses, viroids, prions and lichens are acellular or symbiotic entities not placed in the five-kingdom classification.", "Step 1: Viruses have a protein coat (capsid) and genetic material (DNA or RNA, never both). Step 2: Viroids (discovered by T.O. Diener) are infectious agents smaller than viruses, consisting of free RNA without a protein coat. Step 3: Prions are abnormally folded infectious proteins causing neurodegenerative diseases.", "NEET Trap: Viroid RNA has low molecular weight and no protein coat. Viruses causing plant diseases usually have single-stranded RNA.", "Which of the following lacks a protein coat and consists only of free RNA?", "Prion|Virus|Viroid|Bacteriophage", 2, "Viroids are infectious agents discovered by T.O. Diener that consist of a short, circular, free RNA molecule of low molecular weight without any protein coat."],

    # c08 Cell: The Unit of Life (2)
    ["BIO-C08-03", "c08", "Cell: The Unit of Life", "Endomembrane System", "ER, Golgi, Lysosomes & Vacuoles", "The endomembrane system includes organelles whose functions are coordinated.", "Step 1: Rough ER (has ribosomes) synthesizes proteins; Smooth ER synthesizes lipids/steroids. Step 2: Golgi apparatus packages materials into vesicles (cis face to trans face) and forms glycoproteins/glycolipids. Step 3: Lysosomes are membrane-bound vesicular structures containing hydrolytic enzymes (acid hydrolases). Step 4: Vacuoles store water, sap, excretory products (tonoplast is the membrane).", "NEET Trap: Mitochondria, chloroplasts, and peroxisomes are NOT part of the endomembrane system because their functions are not coordinated with the ER/Golgi.", "Which of the following is NOT a part of the endomembrane system?", "Golgi complex|Endoplasmic reticulum|Mitochondria|Lysosomes", 2, "Mitochondria, chloroplasts, and peroxisomes are not considered part of the endomembrane system because their functions are not coordinated with it."],
    ["BIO-C08-04", "c08", "Cell: The Unit of Life", "Nucleus", "Chromatin & Chromosomes", "The nucleus is the controlling center of the eukaryotic cell containing the genetic material.", "Step 1: Nuclear envelope is a double membrane with nuclear pores for transport of RNA/proteins. Step 2: Nucleoplasm contains nucleolus (site of active rRNA synthesis) and chromatin. Step 3: During cell division, chromatin condenses into chromosomes (DNA + histones). Step 4: Centromere has kinetochores on sides.", "NEET Trap: The nucleolus is NOT membrane-bound. It is a dense, spherical structure in the nucleoplasm that synthesizes ribosomal RNA (rRNA).", "The site of active ribosomal RNA (rRNA) synthesis is:", "Nucleoplasm|Nucleolus|Ribosomes|Mitochondria", 1, "The nucleolus is a non-membrane bound, spherical structure within the nucleus that serves as the site for active rRNA synthesis."],

    # c09 Biomolecules (2)
    ["BIO-C09-02", "c09", "Biomolecules", "Enzymes", "Properties & Factors Affecting Activity", "Enzymes are biocatalysts, mostly proteins, that accelerate metabolic reactions.", "Step 1: Enzymes lower the activation energy of a reaction. Step 2: High temperature destroys enzymatic activity by denaturing proteins. Step 3: Competitive inhibitors closely resemble the substrate and compete for the active site (e.g., malonate inhibiting succinate dehydrogenase).", "NEET Trap: Competitive inhibition can be overcome by increasing the substrate concentration. Non-competitive cannot.", "Which of the following is a classical example of competitive inhibition?", "Inhibition of hexokinase by glucose-6-phosphate|Inhibition of succinate dehydrogenase by malonate|Inhibition of cytochrome oxidase by cyanide|Inhibition of phosphofructokinase by ATP", 1, "Malonate structurally resembles succinate and acts as a competitive inhibitor of the enzyme succinate dehydrogenase."],
    ["BIO-C09-03", "c09", "Biomolecules", "Nucleic Acids", "DNA & RNA Structure", "Nucleic acids are polynucleotides consisting of a nitrogenous base, a pentose sugar, and a phosphate group.", "Step 1: Purines (Adenine, Guanine) have a double-ring structure; Pyrimidines (Cytosine, Uracil, Thymine) have a single ring. Step 2: A nucleoside is a base linked to sugar via an N-glycosidic bond. Step 3: A nucleotide is a nucleoside linked to phosphate via a phosphodiester bond. Step 4: DNA is a double helix (Watson-Crick model) with antiparallel strands.", "NEET Trap: Thymine is present only in DNA, Uracil only in RNA. A phosphodiester bond links the 3'-carbon of one sugar to the 5'-carbon of the next.", "The linkage that connects the 3' carbon of one sugar to the 5' carbon of the adjacent sugar in a nucleic acid is called:", "Peptide bond|Glycosidic bond|Phosphodiester bond|Hydrogen bond", 2, "In a polynucleotide chain, successive nucleotides are linked by a 3'-5' phosphodiester linkage."],

    # c10 Cell Cycle and Cell Division (2)
    ["BIO-C10-02", "c10", "Cell Cycle and Cell Division", "Meiosis I", "Prophase I Stages", "Prophase I of meiosis is typically longer and more complex, subdivided into five phases based on chromosomal behavior.", "Step 1: Leptotene (chromosomes become visible). Step 2: Zygotene (pairing/synapsis of homologous chromosomes forming bivalents/tetrads; synaptonemal complex forms). Step 3: Pachytene (crossing over occurs at recombination nodules). Step 4: Diplotene (dissolution of synaptonemal complex; chiasmata visible). Step 5: Diakinesis (terminalisation of chiasmata).", "NEET Trap: Crossing over is an enzyme-mediated process (recombinase) occurring in Pachytene. Chiasmata are X-shaped structures visible in Diplotene.", "During which stage of Prophase I does crossing over occur between non-sister chromatids of homologous chromosomes?", "Zygotene|Pachytene|Diplotene|Diakinesis", 1, "Crossing over, an enzyme-mediated process, occurs during the pachytene stage of prophase I in meiosis."],
    ["BIO-C10-03", "c10", "Cell Cycle and Cell Division", "Mitosis", "Phases of Mitosis", "Mitosis (equational division) occurs in somatic cells to maintain the chromosome number.", "Step 1: Prophase (chromatin condenses, nuclear envelope breaks down). Step 2: Metaphase (chromosomes align at the equator/metaphase plate; spindle fibres attach to kinetochores). Step 3: Anaphase (centromeres split, sister chromatids move to opposite poles). Step 4: Telophase (chromosomes decondense, nuclear envelope reforms).", "NEET Trap: The centromere splits only during Anaphase of mitosis and Anaphase II of meiosis, but NOT during Anaphase I of meiosis (where homologous chromosomes separate).", "In which phase of mitosis do the centromeres split and sister chromatids separate?", "Prophase|Metaphase|Anaphase|Telophase", 2, "During anaphase, the centromere of each chromosome splits, allowing sister chromatids to separate and move toward opposite poles."],

    # c12 Respiration in Plants (2)
    ["BIO-C12-03", "c12", "Respiration in Plants", "TCA Cycle (Krebs Cycle)", "Mitochondrial Matrix Reactions", "The Tricarboxylic Acid cycle occurs in the mitochondrial matrix and oxidizes Acetyl CoA to CO2.", "Step 1: Acetyl CoA (2C) condenses with Oxaloacetic acid (4C) and water to form Citric acid (6C) using citrate synthase. Step 2: Isomerisation to isocitrate. Step 3: Two successive decarboxylations form alpha-ketoglutaric acid (5C) and succinyl CoA (4C). Step 4: Regeneration of OAA produces 1 ATP/GTP, 3 NADH, and 1 FADH2 per turn.", "NEET Trap: Substrate-level phosphorylation in the Krebs cycle occurs when succinyl-CoA is converted to succinic acid (yielding 1 GTP/ATP).", "In the Krebs cycle, substrate-level phosphorylation occurs during the conversion of:", "Citric acid to alpha-ketoglutaric acid|Succinyl-CoA to succinic acid|Succinic acid to fumaric acid|Malic acid to oxaloacetic acid", 1, "Substrate-level phosphorylation directly generates one GTP/ATP molecule when succinyl-CoA is converted into succinic acid."],
    ["BIO-C12-04", "c12", "Respiration in Plants", "Electron Transport System (ETS)", "Oxidative Phosphorylation", "ETS in the inner mitochondrial membrane transfers electrons from NADH and FADH2 to oxygen.", "Step 1: Complex I (NADH dehydrogenase) oxidizes NADH. Step 2: Complex II (Succinate dehydrogenase) oxidizes FADH2. Step 3: Ubiquinone transfers electrons to Complex III (Cytochrome bc1). Step 4: Cytochrome c transfers electrons to Complex IV (Cytochrome c oxidase containing Cu centers). Step 5: Complex V (ATP synthase) produces ATP as protons flow back to the matrix.", "NEET Trap: The final electron acceptor in the mitochondrial ETS is molecular oxygen (O2), which combines with H+ to form metabolic water. Cytochrome c is a small, mobile protein.", "Which of the following acts as the final electron acceptor in the mitochondrial electron transport chain?", "Cytochrome b|Cytochrome c|Oxygen|NAD+", 2, "Molecular oxygen acts as the final electron acceptor in the aerobic electron transport system, combining with protons to form water."]
]

df = pd.read_csv('data/neet_knowledge_base.csv')
new_df = pd.DataFrame(new_data, columns=df.columns)
df = pd.concat([df, new_df], ignore_index=True)
df.to_csv('data/neet_knowledge_base.csv', index=False)
print("Added 13 more rows. Total rows:", len(df))
